{% set versions = {
    "0.8.6": "101396107b7f49c765f5413386ad81e52cef3e6e6a0d31876b1a0bd41cc6c125"
} %}


{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "pineappl")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: "https://github.com/NNPDF/pineappl/archive/refs/tags/v{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}

    - make
    - rust
    - cargo-c
 
  host:
    - python
    - pip

  run:
    - python

about:
  home: "https://nnpdf.github.io/pineappl"
  license: "GPL-3.0"
  summary: "This repository contains programs, libraries and interfaces to read and write PineAPPL interpolation grids, which store theoretical predictions for high-energy collisions independently from their PDFs and the strong coupling."
  description: |
    This repository contains programs, libraries and interfaces to read and write PineAPPL interpolation grids, which store theoretical predictions for high-energy collisions independently from their PDFs and the strong coupling.
    PineAPPL grids are generated by Monte Carlo generators, and the grids in turn can be convolved with PDFs to produce tables and plots, such as the following one:

extra:
  recipe-maintainers:
    - meiyasan
